QUESTIONS = [
	("Expend energy, enjoy groups", "Conserve energy, enjoy one-on-one"),
	("Interpret literally", "Look for meaning and possibilities"),
	("Logical, thinking, questioning", "Empathetic, feeling, accommodating"),
	("Organized, orderly", "Flexible, adaptable"),
	("More outgoing, think out loud", "More reserved, think to yourself"),
	("Practical, realistic, frank", "Tactful, kind, encouraging"),
	("Candid, straightforward, frank", "Tactful, kind, encouraging"),
	("Plan, schedule", "Unplanned, spontaneous"),
	("Seek many tasks, public activities", "Seek private, solitary activities"),
	("Standard, usual, convention", "Different, novel, unique"),
	("Firm, tend to criticize, hold the line", "Gentle, tend to appreciate, conciliate"),
	("Regulated, structured", "Easy-going, live and let live"),
	("External, communicative, express yourself", "Internal, reticent, keep to yourself"),
	("Focus on here-and-now", "Look to the future, big picture"),
	("Tough-minded, just", "Tender-hearted, merciful"),
	("Preparation, plan ahead", "Go with the flow, adapt as you go"),
	("Active, initiate", "Reflective, deliberate"),
	("Facts, things, what is", "Ideas, dreams, what could be, philosophical"),